// Code generated by pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package remotecertificate

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type CertThumbPrint struct {
	pulumi.CustomResourceState

	Hash   pulumi.StringOutput `pulumi:"hash"`
	Port   pulumi.IntOutput    `pulumi:"port"`
	Server pulumi.StringOutput `pulumi:"server"`
}

// NewCertThumbPrint registers a new resource with the given unique name, arguments, and options.
func NewCertThumbPrint(ctx *pulumi.Context,
	name string, args *CertThumbPrintArgs, opts ...pulumi.ResourceOption) (*CertThumbPrint, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Port == nil {
		return nil, errors.New("invalid value for required argument 'Port'")
	}
	if args.Server == nil {
		return nil, errors.New("invalid value for required argument 'Server'")
	}
	var resource CertThumbPrint
	err := ctx.RegisterResource("remotecertificate:index:CertThumbPrint", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCertThumbPrint gets an existing CertThumbPrint resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCertThumbPrint(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CertThumbPrintState, opts ...pulumi.ResourceOption) (*CertThumbPrint, error) {
	var resource CertThumbPrint
	err := ctx.ReadResource("remotecertificate:index:CertThumbPrint", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CertThumbPrint resources.
type certThumbPrintState struct {
}

type CertThumbPrintState struct {
}

func (CertThumbPrintState) ElementType() reflect.Type {
	return reflect.TypeOf((*certThumbPrintState)(nil)).Elem()
}

type certThumbPrintArgs struct {
	Port   int    `pulumi:"port"`
	Server string `pulumi:"server"`
}

// The set of arguments for constructing a CertThumbPrint resource.
type CertThumbPrintArgs struct {
	Port   pulumi.IntInput
	Server pulumi.StringInput
}

func (CertThumbPrintArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*certThumbPrintArgs)(nil)).Elem()
}

type CertThumbPrintInput interface {
	pulumi.Input

	ToCertThumbPrintOutput() CertThumbPrintOutput
	ToCertThumbPrintOutputWithContext(ctx context.Context) CertThumbPrintOutput
}

func (*CertThumbPrint) ElementType() reflect.Type {
	return reflect.TypeOf((**CertThumbPrint)(nil)).Elem()
}

func (i *CertThumbPrint) ToCertThumbPrintOutput() CertThumbPrintOutput {
	return i.ToCertThumbPrintOutputWithContext(context.Background())
}

func (i *CertThumbPrint) ToCertThumbPrintOutputWithContext(ctx context.Context) CertThumbPrintOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CertThumbPrintOutput)
}

type CertThumbPrintOutput struct{ *pulumi.OutputState }

func (CertThumbPrintOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CertThumbPrint)(nil)).Elem()
}

func (o CertThumbPrintOutput) ToCertThumbPrintOutput() CertThumbPrintOutput {
	return o
}

func (o CertThumbPrintOutput) ToCertThumbPrintOutputWithContext(ctx context.Context) CertThumbPrintOutput {
	return o
}

func (o CertThumbPrintOutput) Hash() pulumi.StringOutput {
	return o.ApplyT(func(v *CertThumbPrint) pulumi.StringOutput { return v.Hash }).(pulumi.StringOutput)
}

func (o CertThumbPrintOutput) Port() pulumi.IntOutput {
	return o.ApplyT(func(v *CertThumbPrint) pulumi.IntOutput { return v.Port }).(pulumi.IntOutput)
}

func (o CertThumbPrintOutput) Server() pulumi.StringOutput {
	return o.ApplyT(func(v *CertThumbPrint) pulumi.StringOutput { return v.Server }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CertThumbPrintInput)(nil)).Elem(), &CertThumbPrint{})
	pulumi.RegisterOutputType(CertThumbPrintOutput{})
}
