// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CertThumbPrintArgs } from "./certThumbPrint";
export type CertThumbPrint = import("./certThumbPrint").CertThumbPrint;
export const CertThumbPrint: typeof import("./certThumbPrint").CertThumbPrint = null as any;
utilities.lazyLoad(exports, ["CertThumbPrint"], () => require("./certThumbPrint"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "remotecertificate:index:CertThumbPrint":
                return new CertThumbPrint(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("remotecertificate", "index", _module)
pulumi.runtime.registerResourcePackage("remotecertificate", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:remotecertificate") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
